// Core vocabulary by category, one list per language: [word, meaning].
// The words from the Brighter Path lessons are merged in by build.js; a lesson word that is already here keeps this category.
module.exports = {
  turkish: {
    'Greetings': [
      ['Merhaba', 'Hello'], ['Selam', 'Hi'], ['Günaydın', 'Good morning'], ['İyi günler', 'Good day'],
      ['İyi akşamlar', 'Good evening'], ['İyi geceler', 'Good night'], ['Hoşça kal', 'Goodbye (said by the one leaving)'],
      ['Güle güle', 'Goodbye (said to the one leaving)'], ['Görüşürüz', 'See you'], ['Nasılsın?', 'How are you?'],
      ['İyiyim, teşekkürler', "I'm fine, thanks"], ['Teşekkür ederim', 'Thank you'], ['Teşekkürler', 'Thanks'],
      ['Lütfen', 'Please'], ['Rica ederim', "You're welcome"], ['Özür dilerim', "I'm sorry"], ['Pardon', 'Excuse me'],
      ['Evet', 'Yes'], ['Hayır', 'No'], ['Tamam', 'Okay'], ['Hoş geldiniz', 'Welcome'], ['Memnun oldum', 'Nice to meet you'],
      ['Adın ne?', "What's your name?"], ['Benim adım Ali', 'My name is Ali'],
    ],
    'Numbers': [
      ['Sıfır', 'Zero · 0'], ['Bir', 'One · 1'], ['İki', 'Two · 2'], ['Üç', 'Three · 3'], ['Dört', 'Four · 4'], ['Beş', 'Five · 5'],
      ['Altı', 'Six · 6'], ['Yedi', 'Seven · 7'], ['Sekiz', 'Eight · 8'], ['Dokuz', 'Nine · 9'], ['On', 'Ten · 10'],
      ['On bir', 'Eleven · 11'], ['On iki', 'Twelve · 12'], ['Yirmi', 'Twenty · 20'], ['Otuz', 'Thirty · 30'], ['Kırk', 'Forty · 40'],
      ['Elli', 'Fifty · 50'], ['Altmış', 'Sixty · 60'], ['Yetmiş', 'Seventy · 70'], ['Seksen', 'Eighty · 80'], ['Doksan', 'Ninety · 90'],
      ['Yüz', 'One hundred · 100'], ['Bin', 'One thousand · 1000'],
    ],
    'Colors': [
      ['Renk', 'Colour'], ['Kırmızı', 'Red'], ['Mavi', 'Blue'], ['Lacivert', 'Navy blue'], ['Yeşil', 'Green'], ['Sarı', 'Yellow'],
      ['Siyah', 'Black'], ['Beyaz', 'White'], ['Turuncu', 'Orange'], ['Mor', 'Purple'], ['Pembe', 'Pink'],
      ['Kahverengi', 'Brown'], ['Gri', 'Grey'],
    ],
    'Family & People': [
      ['Aile', 'Family'], ['Anne', 'Mother'], ['Baba', 'Father'], ['Kardeş', 'Sibling'], ['Abla', 'Older sister'],
      ['Ağabey', 'Older brother'], ['Oğul', 'Son'], ['Kız', 'Daughter · girl'], ['Çocuk', 'Child'], ['Bebek', 'Baby'],
      ['Büyükanne', 'Grandmother'], ['Büyükbaba', 'Grandfather'], ['Eş', 'Spouse'], ['Arkadaş', 'Friend'], ['Kadın', 'Woman'],
      ['Adam', 'Man'], ['Öğretmen', 'Teacher'], ['Öğrenci', 'Student'], ['Doktor', 'Doctor'],
    ],
    'Animals': [
      ['Kedi', 'Cat'], ['Köpek', 'Dog'], ['Kuş', 'Bird'], ['Balık', 'Fish'], ['At', 'Horse'], ['İnek', 'Cow'], ['Tavuk', 'Chicken'],
      ['Koyun', 'Sheep'], ['Fare', 'Mouse'], ['Tavşan', 'Rabbit'], ['Ayı', 'Bear'], ['Aslan', 'Lion'], ['Maymun', 'Monkey'],
      ['Fil', 'Elephant'], ['Yılan', 'Snake'], ['Kelebek', 'Butterfly'],
    ],
    'Food & Drink': [
      ['Su', 'Water'], ['Çay', 'Tea'], ['Kahve', 'Coffee'], ['Süt', 'Milk'], ['Ekmek', 'Bread'], ['Peynir', 'Cheese'],
      ['Yumurta', 'Egg'], ['Et', 'Meat'], ['Pilav', 'Rice (cooked)'], ['Çorba', 'Soup'], ['Meyve', 'Fruit'], ['Elma', 'Apple'],
      ['Portakal', 'Orange (fruit)'], ['Muz', 'Banana'], ['Sebze', 'Vegetable'], ['Domates', 'Tomato'], ['Şeker', 'Sugar'],
      ['Tuz', 'Salt'], ['Bal', 'Honey'], ['Kahvaltı', 'Breakfast'], ['Hesap', 'The bill'],
    ],
    'Home & Objects': [
      ['Ev', 'House · home'], ['Oda', 'Room'], ['Mutfak', 'Kitchen'], ['Banyo', 'Bathroom'], ['Kapı', 'Door'], ['Pencere', 'Window'],
      ['Masa', 'Table'], ['Sandalye', 'Chair'], ['Yatak', 'Bed'], ['Lamba', 'Lamp'], ['Kitap', 'Book'], ['Kalem', 'Pen'],
      ['Çanta', 'Bag'], ['Anahtar', 'Key'], ['Telefon', 'Phone'], ['Bardak', 'Glass (for drinking)'], ['Fincan', 'Cup'],
      ['Tabak', 'Plate'], ['Bahçe', 'Garden'],
    ],
    'Places': [
      ['Okul', 'School'], ['Hastane', 'Hospital'], ['Market', 'Supermarket'], ['Lokanta', 'Restaurant'], ['Kafe', 'Café'],
      ['Park', 'Park'], ['Sokak', 'Street'], ['Şehir', 'City'], ['Köy', 'Village'], ['Deniz', 'Sea'], ['Dağ', 'Mountain'],
      ['Plaj', 'Beach'], ['Otel', 'Hotel'], ['Havalimanı', 'Airport'], ['İstasyon', 'Station'], ['Banka', 'Bank'],
      ['Cami', 'Mosque'], ['Çarşı', 'Bazaar · market'], ['İş', 'Work · job'], ['Ülke', 'Country'],
    ],
    'Time & Days': [
      ['Pazartesi', 'Monday'], ['Salı', 'Tuesday'], ['Çarşamba', 'Wednesday'], ['Perşembe', 'Thursday'], ['Cuma', 'Friday'],
      ['Cumartesi', 'Saturday'], ['Pazar', 'Sunday'], ['Bugün', 'Today'], ['Yarın', 'Tomorrow'], ['Dün', 'Yesterday'],
      ['Sabah', 'Morning'], ['Öğlen', 'Noon'], ['Akşam', 'Evening'], ['Gece', 'Night'], ['Gün', 'Day'], ['Hafta', 'Week'],
      ['Ay', 'Month · moon'], ['Yıl', 'Year'], ['Saat', 'Hour · clock'], ['Dakika', 'Minute'], ['Şimdi', 'Now'],
      ['Sonra', 'Later · after'], ['Saat kaç?', 'What time is it?'],
    ],
    'Basics': [
      ['Ben', 'I'], ['Sen', 'You (informal)'], ['O', 'He · she · it'], ['Biz', 'We'], ['Siz', 'You (plural · formal)'],
      ['Onlar', 'They'], ['Bu', 'This'], ['Şu', 'That'], ['Ne?', 'What?'], ['Kim?', 'Who?'], ['Nerede?', 'Where?'],
      ['Nereye?', 'Where to?'], ['Ne zaman?', 'When?'], ['Neden?', 'Why?'], ['Nasıl?', 'How?'], ['Kaç?', 'How many?'],
      ['Hangi?', 'Which?'], ['Var', 'There is · have'], ['Yok', "There isn't · don't have"], ['Ve', 'And'], ['Ama', 'But'],
      ['Çok', 'Very · a lot'], ['Biraz', 'A little'],
    ],
    'Adjectives': [
      ['Büyük', 'Big'], ['Küçük', 'Small'], ['Güzel', 'Beautiful · nice'], ['İyi', 'Good'], ['Kötü', 'Bad'], ['Sıcak', 'Hot'],
      ['Soğuk', 'Cold'], ['Yeni', 'New'], ['Eski', 'Old (things)'], ['Yaşlı', 'Old (people)'], ['Genç', 'Young'],
      ['Uzun', 'Long · tall'], ['Kısa', 'Short'], ['Hızlı', 'Fast'], ['Yavaş', 'Slow'], ['Kolay', 'Easy'], ['Zor', 'Difficult'],
      ['Mutlu', 'Happy'], ['Üzgün', 'Sad'], ['Yorgun', 'Tired'], ['Aç', 'Hungry'], ['Tok', 'Full (not hungry)'],
      ['Pahalı', 'Expensive'], ['Ucuz', 'Cheap'],
    ],
    'Verbs 1': [
      ['Gelmek', 'To come'], ['Gitmek', 'To go'], ['Yapmak', 'To do · to make'], ['Olmak', 'To be · to become'],
      ['Yemek', 'To eat · food, meal'], ['İçmek', 'To drink'], ['Görmek', 'To see'], ['Bakmak', 'To look'], ['Bilmek', 'To know'],
      ['İstemek', 'To want'], ['Sevmek', 'To love · to like'], ['Almak', 'To take · to buy'], ['Vermek', 'To give'],
      ['Okumak', 'To read'], ['Yazmak', 'To write'], ['Konuşmak', 'To speak'], ['Anlamak', 'To understand'],
      ['Çalışmak', 'To work · to study'], ['Uyumak', 'To sleep'], ['Oturmak', 'To sit · to live (somewhere)'],
    ],
    'Verbs 2': [
      ['Duymak', 'To hear'], ['Söylemek', 'To say'], ['Sormak', 'To ask'], ['Beklemek', 'To wait'], ['Açmak', 'To open'],
      ['Kapatmak', 'To close'], ['Başlamak', 'To start'], ['Bitirmek', 'To finish'], ['Koşmak', 'To run'], ['Yürümek', 'To walk'],
      ['Yüzmek', 'To swim'], ['Oynamak', 'To play'], ['Öğrenmek', 'To learn'], ['Öğretmek', 'To teach'], ['Kalkmak', 'To get up'],
      ['Dinlemek', 'To listen'], ['İzlemek', 'To watch'], ['Pişirmek', 'To cook'], ['Yaşamak', 'To live'], ['Getirmek', 'To bring'],
    ],
  },

  russian: {
    'Alphabet': [
      ['Ё', 'Sounds like yo'], ['З', 'Sounds like z'], ['Й', 'Sounds like y (short i, as in boy)'], ['Ф', 'Sounds like f'],
      ['Х', 'Sounds like kh (as in loch)'], ['Ц', 'Sounds like ts'], ['Щ', 'Sounds like shch (a long, soft sh)'],
      ['Ъ', 'Hard sign (no sound of its own)'], ['Ы', 'Sounds like y (between i and u)'], ['Ь', 'Soft sign (softens the letter before)'],
      ['Э', 'Sounds like e (as in bet)'], ['Ю', 'Sounds like yu'],
    ],
    'Greetings': [
      ['Привет', 'Hi'], ['Здравствуйте', 'Hello (formal)'], ['Доброе утро', 'Good morning'], ['Добрый день', 'Good afternoon'],
      ['Добрый вечер', 'Good evening'], ['Спокойной ночи', 'Good night'], ['До свидания', 'Goodbye'], ['Пока', 'Bye (informal)'],
      ['Как дела?', 'How are you?'], ['Хорошо', 'Good · fine'], ['Спасибо', 'Thank you'], ['Пожалуйста', "Please · you're welcome"],
      ['Извините', 'Excuse me · sorry'], ['Да', 'Yes'], ['Нет', 'No'], ['Очень приятно', 'Nice to meet you'],
      ['Как тебя зовут?', "What's your name?"], ['Меня зовут Аня', 'My name is Anya'], ['Добро пожаловать', 'Welcome'], ['Ладно', 'Okay'],
    ],
    'Numbers': [
      ['Ноль', 'Zero · 0'], ['Один', 'One · 1'], ['Два', 'Two · 2'], ['Три', 'Three · 3'], ['Четыре', 'Four · 4'], ['Пять', 'Five · 5'],
      ['Шесть', 'Six · 6'], ['Семь', 'Seven · 7'], ['Восемь', 'Eight · 8'], ['Девять', 'Nine · 9'], ['Десять', 'Ten · 10'],
      ['Одиннадцать', 'Eleven · 11'], ['Двенадцать', 'Twelve · 12'], ['Двадцать', 'Twenty · 20'], ['Тридцать', 'Thirty · 30'],
      ['Сорок', 'Forty · 40'], ['Пятьдесят', 'Fifty · 50'], ['Сто', 'One hundred · 100'], ['Тысяча', 'One thousand · 1000'],
    ],
    'Colors': [
      ['Цвет', 'Colour'], ['Красный', 'Red'], ['Синий', 'Blue (dark)'], ['Голубой', 'Light blue'], ['Зелёный', 'Green'],
      ['Жёлтый', 'Yellow'], ['Чёрный', 'Black'], ['Белый', 'White'], ['Оранжевый', 'Orange'], ['Фиолетовый', 'Purple'],
      ['Розовый', 'Pink'], ['Коричневый', 'Brown'], ['Серый', 'Grey'],
    ],
    'Family & People': [
      ['Семья', 'Family'], ['Мама', 'Mum'], ['Папа', 'Dad'], ['Мать', 'Mother'], ['Отец', 'Father'], ['Брат', 'Brother'],
      ['Сестра', 'Sister'], ['Сын', 'Son'], ['Дочь', 'Daughter'], ['Бабушка', 'Grandmother'], ['Дедушка', 'Grandfather'],
      ['Ребёнок', 'Child'], ['Дети', 'Children'], ['Друг', 'Friend (male)'], ['Подруга', 'Friend (female)'], ['Мужчина', 'Man'],
      ['Женщина', 'Woman'], ['Мальчик', 'Boy'], ['Девочка', 'Girl'], ['Студент', 'Student'], ['Учитель', 'Teacher'], ['Врач', 'Doctor'],
    ],
    'Animals': [
      ['Кот', 'Cat (tomcat)'], ['Кошка', 'Cat (female · in general)'], ['Собака', 'Dog'], ['Птица', 'Bird'], ['Рыба', 'Fish'],
      ['Лошадь', 'Horse'], ['Корова', 'Cow'], ['Свинья', 'Pig'], ['Курица', 'Hen · chicken'], ['Мышь', 'Mouse'], ['Медведь', 'Bear'],
      ['Волк', 'Wolf'], ['Лиса', 'Fox'], ['Заяц', 'Hare'],
    ],
    'Food & Drink': [
      ['Еда', 'Food'], ['Вода', 'Water'], ['Чай', 'Tea'], ['Кофе', 'Coffee'], ['Молоко', 'Milk'], ['Сок', 'Juice'], ['Хлеб', 'Bread'],
      ['Сыр', 'Cheese'], ['Яйцо', 'Egg'], ['Мясо', 'Meat'], ['Суп', 'Soup'], ['Каша', 'Porridge'], ['Картошка', 'Potatoes'],
      ['Яблоко', 'Apple'], ['Банан', 'Banana'], ['Торт', 'Cake'], ['Сахар', 'Sugar'], ['Соль', 'Salt'], ['Завтрак', 'Breakfast'],
      ['Обед', 'Lunch'], ['Ужин', 'Dinner'],
    ],
    'Home & Objects': [
      ['Дом', 'House · home'], ['Квартира', 'Flat · apartment'], ['Комната', 'Room'], ['Кухня', 'Kitchen'], ['Окно', 'Window'],
      ['Дверь', 'Door'], ['Стол', 'Table'], ['Стул', 'Chair'], ['Кровать', 'Bed'], ['Лампа', 'Lamp'], ['Книга', 'Book'],
      ['Ручка', 'Pen'], ['Телефон', 'Phone'], ['Ключ', 'Key'], ['Сумка', 'Bag'], ['Чашка', 'Cup'],
    ],
    'Places': [
      ['Город', 'City · town'], ['Улица', 'Street'], ['Парк', 'Park'], ['Магазин', 'Shop'], ['Кафе', 'Café'], ['Ресторан', 'Restaurant'],
      ['Школа', 'School'], ['Университет', 'University'], ['Работа', 'Work · job'], ['Метро', 'Metro'], ['Вокзал', 'Railway station'],
      ['Аэропорт', 'Airport'], ['Больница', 'Hospital'], ['Банк', 'Bank'], ['Гостиница', 'Hotel'], ['Музей', 'Museum'],
      ['Библиотека', 'Library'], ['Почта', 'Post office'], ['Страна', 'Country'], ['Россия', 'Russia'], ['Москва', 'Moscow'],
    ],
    'Time & Days': [
      ['Понедельник', 'Monday'], ['Вторник', 'Tuesday'], ['Среда', 'Wednesday'], ['Четверг', 'Thursday'], ['Пятница', 'Friday'],
      ['Суббота', 'Saturday'], ['Воскресенье', 'Sunday'], ['Сегодня', 'Today'], ['Завтра', 'Tomorrow'], ['Вчера', 'Yesterday'],
      ['Утро', 'Morning'], ['День', 'Day'], ['Вечер', 'Evening'], ['Ночь', 'Night'], ['Утром', 'In the morning'],
      ['Днём', 'In the afternoon'], ['Вечером', 'In the evening'], ['Неделя', 'Week'], ['Месяц', 'Month'], ['Год', 'Year'],
      ['Час', 'Hour'], ['Минута', 'Minute'], ['Сейчас', 'Now'], ['Потом', 'Later · then'], ['Который час?', 'What time is it?'],
    ],
    'Basics': [
      ['Я', 'I'], ['Ты', 'You (informal)'], ['Он', 'He'], ['Она', 'She'], ['Оно', 'It'], ['Мы', 'We'], ['Вы', 'You (formal · plural)'],
      ['Они', 'They'], ['Это', 'This · this is'], ['Что?', 'What?'], ['Кто?', 'Who?'], ['Где?', 'Where?'], ['Куда?', 'Where to?'],
      ['Когда?', 'When?'], ['Почему?', 'Why?'], ['Как?', 'How?'], ['Сколько?', 'How much? · how many?'], ['И', 'And'], ['Но', 'But'],
      ['Или', 'Or'], ['Очень', 'Very'], ['Не', 'Not'],
    ],
    'Adjectives': [
      ['Большой', 'Big'], ['Маленький', 'Small'], ['Хороший', 'Good'], ['Плохой', 'Bad'], ['Новый', 'New'], ['Старый', 'Old'],
      ['Молодой', 'Young'], ['Красивый', 'Beautiful'], ['Горячий', 'Hot'], ['Холодный', 'Cold'], ['Длинный', 'Long'],
      ['Короткий', 'Short'], ['Быстрый', 'Fast'], ['Медленный', 'Slow'], ['Лёгкий', 'Easy · light'], ['Трудный', 'Difficult'],
      ['Счастливый', 'Happy'], ['Грустный', 'Sad'], ['Дорогой', 'Expensive · dear'], ['Дешёвый', 'Cheap'], ['Интересный', 'Interesting'],
    ],
    'Verbs 1': [
      ['Быть', 'To be'], ['Делать', 'To do · to make'], ['Говорить', 'To speak · to say'], ['Знать', 'To know'],
      ['Понимать', 'To understand'], ['Хотеть', 'To want'], ['Любить', 'To love · to like'], ['Жить', 'To live'],
      ['Работать', 'To work'], ['Читать', 'To read'], ['Писать', 'To write'], ['Идти', 'To go (on foot)'],
      ['Ехать', 'To go (by transport)'], ['Есть', 'To eat'], ['Пить', 'To drink'], ['Спать', 'To sleep'], ['Видеть', 'To see'],
      ['Смотреть', 'To watch · to look'], ['Слушать', 'To listen'], ['Думать', 'To think'],
    ],
    'Verbs 2': [
      ['Играть', 'To play'], ['Учить', 'To learn · to teach'], ['Отдыхать', 'To rest'], ['Покупать', 'To buy'], ['Давать', 'To give'],
      ['Брать', 'To take'], ['Открывать', 'To open'], ['Закрывать', 'To close'], ['Начинать', 'To begin'], ['Ждать', 'To wait'],
      ['Спрашивать', 'To ask'], ['Отвечать', 'To answer'], ['Готовить', 'To cook'], ['Гулять', 'To go for a walk'],
      ['Бегать', 'To run'], ['Плавать', 'To swim'], ['Помнить', 'To remember'], ['Звонить', 'To call · to ring'],
      ['Нравиться', 'To be liked (мне нравится = I like)'],
    ],
  },

  italian: {
    'Greetings': [
      ['Ciao', 'Hi · bye'], ['Salve', 'Hello'], ['Buongiorno', 'Good morning'], ['Buonasera', 'Good evening'], ['Buonanotte', 'Good night'],
      ['Arrivederci', 'Goodbye'], ['A presto', 'See you soon'], ['Come stai?', 'How are you? (informal)'],
      ['Come sta?', 'How are you? (formal)'], ['Bene, grazie', 'Fine, thanks'], ['Grazie', 'Thank you'], ['Prego', "You're welcome"],
      ['Per favore', 'Please'], ['Scusa', 'Sorry (informal)'], ['Mi scusi', 'Excuse me (formal)'], ['Sì', 'Yes'], ['No', 'No'],
      ['Piacere', 'Nice to meet you'], ['Come ti chiami?', "What's your name?"], ['Mi chiamo Luca', 'My name is Luca'],
      ['Benvenuto', 'Welcome'],
    ],
    'Numbers': [
      ['Zero', 'Zero · 0'], ['Uno', 'One · 1'], ['Due', 'Two · 2'], ['Tre', 'Three · 3'], ['Quattro', 'Four · 4'], ['Cinque', 'Five · 5'],
      ['Sei', 'Six · 6'], ['Sette', 'Seven · 7'], ['Otto', 'Eight · 8'], ['Nove', 'Nine · 9'], ['Dieci', 'Ten · 10'],
      ['Undici', 'Eleven · 11'], ['Dodici', 'Twelve · 12'], ['Venti', 'Twenty · 20'], ['Trenta', 'Thirty · 30'],
      ['Quaranta', 'Forty · 40'], ['Cinquanta', 'Fifty · 50'], ['Cento', 'One hundred · 100'], ['Mille', 'One thousand · 1000'],
    ],
    'Colors': [
      ['Colore', 'Colour'], ['Rosso', 'Red'], ['Blu', 'Blue'], ['Azzurro', 'Light blue'], ['Verde', 'Green'], ['Giallo', 'Yellow'],
      ['Nero', 'Black'], ['Bianco', 'White'], ['Arancione', 'Orange'], ['Viola', 'Purple'], ['Rosa', 'Pink'], ['Marrone', 'Brown'],
      ['Grigio', 'Grey'],
    ],
    'Family & People': [
      ['Famiglia', 'Family'], ['Madre', 'Mother'], ['Padre', 'Father'], ['Mamma', 'Mum'], ['Papà', 'Dad'], ['Fratello', 'Brother'],
      ['Sorella', 'Sister'], ['Figlio', 'Son'], ['Figlia', 'Daughter'], ['Nonno', 'Grandfather'], ['Nonna', 'Grandmother'],
      ['Marito', 'Husband'], ['Moglie', 'Wife'], ['Bambino', 'Child · little boy'], ['Amico', 'Friend (male)'], ['Amica', 'Friend (female)'],
      ['Uomo', 'Man'], ['Donna', 'Woman'], ['Ragazzo', 'Boy · young man'], ['Ragazza', 'Girl · young woman'],
      ['Insegnante', 'Teacher'], ['Medico', 'Doctor'],
    ],
    'Animals': [
      ['Gatto', 'Cat'], ['Cane', 'Dog'], ['Uccello', 'Bird'], ['Pesce', 'Fish'], ['Cavallo', 'Horse'], ['Mucca', 'Cow'],
      ['Maiale', 'Pig'], ['Pecora', 'Sheep'], ['Pollo', 'Chicken'], ['Topo', 'Mouse'], ['Coniglio', 'Rabbit'], ['Orso', 'Bear'],
      ['Leone', 'Lion'], ['Farfalla', 'Butterfly'],
    ],
    'Food & Drink': [
      ['Cibo', 'Food'], ['Acqua', 'Water'], ['Tè', 'Tea'], ['Caffè', 'Coffee'], ['Latte', 'Milk'], ['Vino', 'Wine'], ['Birra', 'Beer'],
      ['Pane', 'Bread'], ['Formaggio', 'Cheese'], ['Uovo', 'Egg'], ['Carne', 'Meat'], ['Pasta', 'Pasta'], ['Riso', 'Rice'],
      ['Frutta', 'Fruit'], ['Mela', 'Apple'], ['Arancia', 'Orange (fruit)'], ['Verdura', 'Vegetables'], ['Zucchero', 'Sugar'],
      ['Sale', 'Salt'], ['Colazione', 'Breakfast'], ['Pranzo', 'Lunch'], ['Cena', 'Dinner'], ['Il conto', 'The bill'],
    ],
    'Home & Objects': [
      ['Casa', 'House · home'], ['Camera', 'Room · bedroom'], ['Cucina', 'Kitchen'], ['Bagno', 'Bathroom'], ['Porta', 'Door'],
      ['Finestra', 'Window'], ['Tavolo', 'Table'], ['Sedia', 'Chair'], ['Letto', 'Bed'], ['Lampada', 'Lamp'], ['Libro', 'Book'],
      ['Penna', 'Pen'], ['Borsa', 'Bag'], ['Chiave', 'Key'], ['Telefono', 'Phone'], ['Tazza', 'Cup'], ['Bicchiere', 'Glass (for drinking)'],
      ['Piatto', 'Plate'],
    ],
    'Places': [
      ['Città', 'City · town'], ['Strada', 'Road · street'], ['Piazza', 'Square'], ['Negozio', 'Shop'], ['Supermercato', 'Supermarket'],
      ['Ristorante', 'Restaurant'], ['Bar', 'Café · bar'], ['Scuola', 'School'], ['Ufficio', 'Office'], ['Lavoro', 'Work · job'],
      ['Stazione', 'Station'], ['Aeroporto', 'Airport'], ['Ospedale', 'Hospital'], ['Banca', 'Bank'], ['Albergo', 'Hotel'],
      ['Museo', 'Museum'], ['Chiesa', 'Church'], ['Spiaggia', 'Beach'], ['Mare', 'Sea'], ['Montagna', 'Mountain'],
      ['Paese', 'Country · village'],
    ],
    'Time & Days': [
      ['Lunedì', 'Monday'], ['Martedì', 'Tuesday'], ['Mercoledì', 'Wednesday'], ['Giovedì', 'Thursday'], ['Venerdì', 'Friday'],
      ['Sabato', 'Saturday'], ['Domenica', 'Sunday'], ['Oggi', 'Today'], ['Domani', 'Tomorrow'], ['Ieri', 'Yesterday'],
      ['Mattina', 'Morning'], ['Pomeriggio', 'Afternoon'], ['Sera', 'Evening'], ['Notte', 'Night'], ['Stasera', 'Tonight · this evening'],
      ['Giorno', 'Day'], ['Settimana', 'Week'], ['Mese', 'Month'], ['Anno', 'Year'], ['Ora', 'Hour · now'], ['Minuto', 'Minute'],
      ['Adesso', 'Now'], ['Dopo', 'Later · after'], ['Subito', 'Right away'], ['Che ore sono?', 'What time is it?'],
    ],
    'Basics': [
      ['Io', 'I'], ['Tu', 'You (informal)'], ['Lui', 'He'], ['Lei', 'She · you (formal)'], ['Noi', 'We'], ['Voi', 'You (plural)'],
      ['Loro', 'They'], ['Questo', 'This'], ['Quello', 'That'], ['Che cosa?', 'What?'], ['Chi?', 'Who?'], ['Dove?', 'Where?'],
      ['Quando?', 'When?'], ['Perché?', 'Why? · because'], ['Come?', 'How?'], ['Quanto?', 'How much?'], ['Quale?', 'Which?'],
      ['E', 'And'], ['Ma', 'But'], ['O', 'Or'], ['Molto', 'Very · a lot'], ['Anche', 'Also · too'], ['Non', 'Not'],
    ],
    'Adjectives': [
      ['Grande', 'Big'], ['Piccolo', 'Small'], ['Bello', 'Beautiful'], ['Buono', 'Good'], ['Cattivo', 'Bad · naughty'],
      ['Nuovo', 'New'], ['Vecchio', 'Old'], ['Giovane', 'Young'], ['Caldo', 'Hot'], ['Freddo', 'Cold'], ['Lungo', 'Long'],
      ['Corto', 'Short'], ['Veloce', 'Fast'], ['Lento', 'Slow'], ['Facile', 'Easy'], ['Difficile', 'Difficult'], ['Felice', 'Happy'],
      ['Triste', 'Sad'], ['Stanco', 'Tired'], ['Caro', 'Expensive · dear'], ['Economico', 'Cheap'], ['Libero', 'Free'],
      ['Ricco', 'Rich'],
    ],
    'Verbs 1': [
      ['Essere', 'To be'], ['Avere', 'To have'], ['Fare', 'To do · to make'], ['Andare', 'To go'], ['Venire', 'To come'],
      ['Stare', 'To stay · to be'], ['Volere', 'To want'], ['Potere', 'To be able to · can'], ['Dovere', 'To have to · must'],
      ['Sapere', 'To know (facts)'], ['Conoscere', 'To know (people, places)'], ['Dire', 'To say · to tell'], ['Parlare', 'To speak'],
      ['Mangiare', 'To eat'], ['Bere', 'To drink'], ['Dormire', 'To sleep'], ['Vedere', 'To see'], ['Guardare', 'To watch · to look at'],
      ['Capire', 'To understand'], ['Lavorare', 'To work'],
    ],
    'Verbs 2': [
      ['Leggere', 'To read'], ['Scrivere', 'To write'], ['Ascoltare', 'To listen'], ['Aprire', 'To open'], ['Chiudere', 'To close'],
      ['Prendere', 'To take'], ['Dare', 'To give'], ['Comprare', 'To buy'], ['Pagare', 'To pay'], ['Aspettare', 'To wait'],
      ['Chiedere', 'To ask'], ['Rispondere', 'To answer'], ['Cominciare', 'To begin'], ['Finire', 'To finish'], ['Correre', 'To run'],
      ['Camminare', 'To walk'], ['Nuotare', 'To swim'], ['Giocare', 'To play'], ['Imparare', 'To learn'], ['Cucinare', 'To cook'],
      ['Chiamare', 'To call'], ['Aiutare', 'To help'], ['Partire', 'To leave'], ['Arrivare', 'To arrive'],
    ],
  },
};
